site_name: Promplate
site_url: !ENV [SITE_URL, "https://docs.py.promplate.dev"]
repo_url: https://github.com/promplate/core
repo_name: promplate/core
site_description: |-
  templating framework and agent orchestrator that progressively enhances your prompt engineering workflow with minimal dependencies

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.footer
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Open Sans
    code: Fira Code
  icon:
    repo: material/github
    annotation: material/star-four-points-circle
    logo: simple/pypi
  favicon: https://promplate.dev/favicon.png
plugins:
  - search
  - llmstxt:
      full_output: llms-full.txt
      sections:
        Overview:
          - index.md
          - quick-start.md
        API References:
          - references/index.md: API Reference for the `promplate` module
          - references/prompt.md: API Reference for the `promplate.prompt` module
          - references/chain.md: API Reference for the `promplate.chain` module
          - references/llm.md: API Reference for the `promplate.llm` module`
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            heading_level: 2
            members_order: source
            parameter_headings: true
            separate_signature: true
            signature_crossrefs: true
            modernize_annotations: true
            type_parameter_headings: true
            show_submodules: true
            show_root_toc_entry: false
            show_if_no_docstring: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_signature_annotations: true
            show_root_members_full_path: true
            show_signature_type_parameters: true
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: material/email
      link: mailto:me@promplate.dev
    - icon: material/bug
      link: https://github.com/promplate/core/issues
    - icon: material/chat-question
      link: https://github.com/promplate/core/discussions/categories/q-a
    - icon: material/web
      link: https://promplate.dev
    - icon: material/package-down
      link: https://pypi.org/project/promplate/
    - icon: fontawesome/brands/github
      link: https://github.com/promplate
extra_css:
  - stylesheets/extra.css
nav:
  - Overview:
      - index.md
      - quick-start.md
  - API References:
      - "<code>promplate</code>": references/index.md
      - "<code>promplate.prompt</code>": references/prompt.md
      - "<code>promplate.chain</code>": references/chain.md
      - "<code>promplate.llm</code>": references/llm.md
  - Interactive Tutorial: https://promplate.dev/
  - Online Playground: https://promplate.dev/playground
